arms_internship2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from . import views

urlpatterns = [
    # url(r'^$', views.home, name='home'),
    url(r'^$', views.HomeView.as_view(), name='Home'),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^schools/', include('schools.urls', namespace='schools')),
]

schools/urls.py
from django.conf.urls import url
from schools import views

app_name = 'schools'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='school_list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='school_details'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
]

users/urls.py
from django.conf.urls import url
from users import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.users, name='users'),
    url(r'^register/', views.register_users, name='register'),
    url(r'^contact_us/', views.ContactUsView.as_view(), name='contact_us'),
]

schools/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=254)
    principal = models.CharField(max_length=254)
    motto = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('schools:school_details', kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=128)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

schools/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from schools.models import School, Student
from django.urls import reverse_lazy


# Create your views here.


class SchoolListView(ListView):  # default context name is <model_name>_list
    context_object_name = 'schools'
    model = School
    template_name = 'schools/schools.html'


class SchoolDetailView(DetailView):  # default context name is <model_name>
    model = School
    template_name = 'schools/school_details.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'motto')
    model = School


class SchoolUpdateView(UpdateView):
    fields = ('principal',)
    model = School


class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy('schools:school_list')

schools/templates/schools/school_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Delete</title>
</head>
<body>

<h1>Delete {{ school.name }}? </h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <a href="{% url 'schools:school_details' pk=school.pk %}">Cancel</a>
</form>


</body>
</html>

schools/templates/schools/school_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>School Details</title>
</head>
<body>

<h1>School Detail</h1>

<h2>School Name: {{ school.name }}</h2>
<h3>Principal: {{ school.principal }}</h3>
<h3>Motto: {{ school.motto }}</h3>

<h2>Students</h2>

{#remember the model related name#}
{% for student in school.students.all %}
    <p>{{ student.name }} who is {{ student.age }} years old</p>
{% endfor %}

<a href="{% url 'schools:update' pk=school.pk %}">Update</a>

<a href="{% url 'schools:delete' pk=school.pk %}">Delete</a>


</body>
</html>

schools/templates/schools/school_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create School</title>
</head>
<body>

<h1>
    {% if not form.instance.pk %}
        Create School
    {% else %}
        Update School
    {% endif %}
</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    {% if not form.instance.pk %}
        <input type="submit" value="Create School">
    {% else %}
        <input type="submit" value="Update School Details">
    {% endif %}

</form>


</body>
</html>

schools/templates/schools/schools.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>schools</title>
</head>
<body>


{% for school in schools %}

    <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>

{% endfor %}


</body>
</html>